dist: trusty
sudo: false
language: python
cache: pip
matrix:
  include:
  - python: 3.4
    env: REQUIREMENTS=notebook-5_0
  - python: 3.4
    env: REQUIREMENTS=notebook-latest
  - python: 3.5
    env: REQUIREMENTS=notebook-5_2
  - python: 3.5
    env: REQUIREMENTS=notebook-latest
  - python: 3.6
    env: REQUIREMENTS=notebook-5_0
  - python: 3.6
    env: REQUIREMENTS=notebook-5_1
  - python: 3.6
    env: REQUIREMENTS=notebook-5_2
  - python: 3.6
    env: REQUIREMENTS=notebook-5_3
  - python: 3.6
    env: REQUIREMENTS=notebook-latest
before_install: pip install --upgrade pip setuptools disttools pytest
install: "./ci/install-${REQUIREMENTS}.sh"
script: py.test
deploy:
  provider: pypi
  user: yatsu
  password:
    secure: X9ArKy2ZEEHuRmy3C9LZWqypqloxw+lOMGLRCL2bOyxPHO+S0mRrWDVE+Dm/0hwMUc75kjoJdFbax9wU1EC6gpqGYezUyTUohpHy8yDAAyx+it/zq2uAdoLCnKm4VCYFFMq7mGnjGIhrld/bkPOqrZLaekiY6QXpHxgaXs6/ZIAwmBjdubE6fMn2NQbzkfix6/XbA5/MabrkjEaDWRlvSjBKH7/5J8HVKHplcWjkET/z8KpV+hKQeNUgo9qjMiOf8KFUgOY4WWOGY9IJkcv75y2sFiW598C/n3uE8J1B+DSnybQQX61QndHvggRqiR8g6PhaaZdUyye9OqqWM/vXH2tSrmi9rfSoq3XGrJgrtaKxsgkF9LlFu3ukgUJ0tylNRhiDL4YohQXFhD4pmz4GwS65o9ntPieXSafPeVa4tMcvjLDyxK33+e4KJ4QC/WFjtLslOyNG2v5DKJ7sh/ZT89hVdOrDS7WSNBbjtfAhihD8FpxYGboEdty9ACmTHMFGLwO9Dl2sUzrVyhQnFM/XCPARymzkbpKst8v2Hm5PGKeB8K03I0fv7n8p/BoupfNQZTOwaYEjmf1SYXLTikWOz1rkLWX3sqe4FHnAeAiOMeFvlVKxubvYpo11o0ZnDSIlj3acJGIguYW+dM4FSlfQYHlOYTkRPphTGnZwIAdh+rk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
notifications:
  email:
    on_success: never
