dist: trusty

sudo: false

language: python

cache: pip

matrix:
  include:
    - python: 3.4
      env: REQUIREMENTS=notebook-5_0
    - python: 3.4
      env: REQUIREMENTS=notebook-latest
    - python: 3.5
      env: REQUIREMENTS=notebook-5_2
    - python: 3.5
      env: REQUIREMENTS=notebook-latest
    - python: 3.6
      env: REQUIREMENTS=notebook-5_0
    - python: 3.6
      env: REQUIREMENTS=notebook-5_1
    - python: 3.6
      env: REQUIREMENTS=notebook-5_2
    - python: 3.6
      env: REQUIREMENTS=notebook-5_3
    - python: 3.6
      env: REQUIREMENTS=notebook-latest

before_install: pip install --upgrade pytest

install: ./ci/install-${REQUIREMENTS}.sh requirements_dev.in

script: py.test

notifications:
  email:
    on_success: never
